server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_ead_auth_user
    username: postgres
    password: G3rat3c2019
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true